/** Client board / kanban view */
export const board = {
  "tab.board": { en: "Board", es: "Tablero" },
  "tab.gallery": { en: "Gallery", es: "Galería" },
  "tab.profile": { en: "Profile", es: "Perfil" },

  "board.active": { en: "Active", es: "Activo" },
  "board.workingOn": { en: "Your studio is working on {count} design{s}", es: "Tu estudio está trabajando en {count} diseño{s}" },
  "board.updated": { en: "Updated {date}", es: "Actualizado {date}" },
  "board.inTheWorks": { en: "In the works", es: "En proceso" },
  "board.dropHere": { en: "Drop here", es: "Suelta aquí" },
  "board.newRequest": { en: "New Request", es: "Nueva solicitud" },
  "board.emptyTitle": { en: "Your studio is ready", es: "Tu estudio está listo" },
  "board.emptyBody": { en: "What would you like us to design first?", es: "¿Qué diseñamos primero?" },
  "board.emptyCta": { en: "Send your first request and we'll get right to work.", es: "Envía tu primera solicitud y nos ponemos a trabajar." },
  "board.welcomeBack": { en: "Welcome back!", es: "¡Hola de nuevo!" },
  "board.sinceLastVisit": { en: "Since your last visit:", es: "Desde tu última visita:" },
  "board.designsReady": { en: "{count} design{s} ready for you", es: "{count} diseño{s} listo{s} para ti" },
  "board.delivered": { en: "{count} delivered", es: "{count} entregado{s}" },
  "board.updates": { en: "{count} update{s} on your designs", es: "{count} actualización{es} en tus diseños" },
  "board.nothingHere": { en: "Nothing here just yet", es: "Nada por aquí aún" },
  "board.empty.queued": { en: "All caught up!", es: "¡Todo al día!" },
  "board.empty.in_progress": { en: "Your designer is heads-down on your work", es: "Tu diseñador está concentrado en tu trabajo" },
  "board.empty.review": { en: "Nothing to review right now", es: "Nada que revisar por ahora" },
  "board.empty.done": { en: "Completed designs will show up here", es: "Los diseños completados aparecerán aquí" },

  // Client home hero (Vimi Client Journey)
  "home.greeting.morning": { en: "Good morning", es: "Buenos días" },
  "home.greeting.afternoon": { en: "Good afternoon", es: "Buenas tardes" },
  "home.greeting.evening": { en: "Good evening", es: "Buenas noches" },
  "home.summary.review": { en: "{count} for your review", es: "{count} para revisar" },
  "home.summary.inProgress": { en: "{count} in the works", es: "{count} en proceso" },
  "home.card.yourTurn": { en: "YOUR TURN", es: "TU TURNO" },
  "home.needsYou.sub": { en: "Ready for your review", es: "Listo para tu revisión" },
  "home.needsYou.more": { en: "+{count} more waiting", es: "+{count} más esperando" },
  "home.needsYou.cta": { en: "Review now", es: "Revisar ahora" },
} as const;
