/** Request detail page — comments, deliverables, actions */
export const detail = {
  "detail.yourDesigns": { en: "Your Designs", es: "Tus Diseños" },
  "detail.references": { en: "References", es: "Referencias" },
  "detail.comments": { en: "Comments", es: "Comentarios" },
  "detail.activity": { en: "Activity", es: "Actividad" },
  "detail.approve": { en: "Approve", es: "Aprobar" },
  "detail.approving": { en: "Approving...", es: "Aprobando..." },
  "detail.askForChanges": { en: "Ask for Changes", es: "Pedir Cambios" },
  "detail.addComment": { en: "Add a comment...", es: "Añade un comentario..." },
  "detail.noComments": { en: "No messages yet. Say hi, or we'll reach out when we have updates.", es: "Sin mensajes aún. Saluda, o te escribiremos cuando tengamos novedades." },
  "detail.upNext": { en: "You're up next! Your designer will start working on this soon.", es: "¡Estás siguiente! Tu diseñador empezará a trabajar en esto pronto." },
  "detail.downloadAll": { en: "Download All", es: "Descargar Todo" },
  "detail.requested": { en: "Requested", es: "Solicitado" },
  "detail.updated": { en: "Updated", es: "Actualizado" },
  "detail.due": { en: "Due", es: "Fecha límite" },
  "detail.noDescription": { en: "No description provided", es: "Sin descripción" },
  "detail.sendHint": { en: "Enter to send, Shift+Enter for new line", es: "Enter para enviar, Shift+Enter para nueva línea" },
  "detail.complete": { en: "Request Complete", es: "Solicitud Completada" },
  "detail.deliveredOn": { en: "Delivered on", es: "Entregado el" },
  "detail.requestComplete": { en: "Request Complete", es: "Solicitud Completada" },
  "detail.preparingFiles": { en: "Preparing {count} files...", es: "Preparando {count} archivos..." },
  "detail.downloadReady": { en: "Download ready!", es: "¡Descarga lista!" },
  "detail.revealAll": { en: "Reveal All", es: "Mostrar Todo" },
  "detail.uploading": { en: "Uploading...", es: "Subiendo..." },
  "detail.uploadDeliverables": { en: "Upload Deliverables", es: "Subir Diseños" },
  "detail.designsWillAppear": { en: "Your designs will show up here once they're ready.", es: "Tus diseños aparecerán aquí cuando estén listos." },
  "detail.noDeliverables": { en: "No deliverables for this request yet.", es: "Aún no hay diseños para esta solicitud." },
  "detail.startWorking": { en: "Start Working", es: "Empezar" },
  "detail.submitForReview": { en: "Submit for Review", es: "Enviar a Revisión" },
  "detail.markDone": { en: "Mark Done", es: "Marcar Entregado" },
  "detail.markDoneConfirm": { en: "Mark as done?", es: "¿Marcar como entregado?" },
  "detail.markDoneDesc": { en: "This will skip the client review step and mark the request as complete. The client will see it as delivered.", es: "Esto saltará la revisión del cliente y marcará la solicitud como completada." },
  "detail.cancel": { en: "Cancel", es: "Cancelar" },
  "detail.updating": { en: "Updating...", es: "Actualizando..." },
  "detail.approved": { en: "Approved! Your designs are ready to download.", es: "¡Aprobado! Tus diseños están listos para descargar." },
  "detail.statusUpdated": { en: "Status updated", es: "Estado actualizado" },
  "detail.couldntPost": { en: "Couldn't post your comment. Please try again.", es: "No se pudo enviar tu comentario. Inténtalo de nuevo." },
  "detail.couldntUpdate": { en: "Couldn't update status. Please try again.", es: "No se pudo actualizar el estado. Inténtalo de nuevo." },
  "detail.hidden": { en: "Hidden", es: "Oculto" },
  "detail.vimistudio": { en: "Vimi Studio", es: "Vimi Studio" },
  "detail.client": { en: "Client", es: "Cliente" },

  // Quick feedback chips
  "chip.loveIt": { en: "Love it!", es: "¡Me encanta!" },
  "chip.changeColors": { en: "Can we change the colors?", es: "¿Podemos cambiar los colores?" },
  "chip.changeText": { en: "Can we change the text?", es: "¿Podemos cambiar el texto?" },
  "chip.differentLayout": { en: "Can we try a different layout?", es: "¿Podemos probar otro diseño?" },
  "chip.almostThere": { en: "Almost there, small tweaks needed", es: "Casi listo, pequeños ajustes" },

  // Edit mode
  "edit.title": { en: "Edit Request", es: "Editar Solicitud" },
  "edit.save": { en: "Save Changes", es: "Guardar Cambios" },
  "edit.saving": { en: "Saving...", es: "Guardando..." },
  "edit.cancel": { en: "Cancel", es: "Cancelar" },
  "edit.saved": { en: "Changes saved", es: "Cambios guardados" },
} as const;
