/** Request detail page — comments, deliverables, actions */
export const detail = {
  "detail.myRequests": { en: "My Requests", es: "Mis Solicitudes" },
  "detail.backToClient": { en: "Back to Client", es: "Volver al Cliente" },
  "detail.yourDesigns": { en: "Your Designs", es: "Tus Diseños" },
  "detail.references": { en: "References", es: "Referencias" },
  "detail.comments": { en: "Comments", es: "Comentarios" },
  "detail.activity": { en: "Activity", es: "Actividad" },
  "detail.approve": { en: "Approve", es: "Aprobar" },
  "detail.approving": { en: "Approving...", es: "Aprobando..." },
  "detail.askForChanges": { en: "Ask for Changes", es: "Pedir Cambios" },
  "detail.addComment": { en: "Add a comment...", es: "Agrega un comentario..." },
  "detail.noComments": { en: "No messages yet. Say hi, or we'll reach out when we have updates.", es: "Sin mensajes aún. Saluda, o te escribiremos cuando tengamos novedades." },
  "detail.upNext": { en: "We've got this queued up and your designer will start soon.", es: "¡Te toca pronto! Tu diseñador va a empezar con esto en breve." },
  "detail.downloadAll": { en: "Download All", es: "Descargar Todo" },
  "detail.requested": { en: "Requested", es: "Solicitado" },
  "detail.updated": { en: "Updated", es: "Actualizado" },
  "detail.due": { en: "Due", es: "Fecha límite" },
  "detail.noDescription": { en: "No details added yet", es: "Sin detalles aún" },
  "detail.sendHint": { en: "Enter to send, Shift+Enter for new line", es: "Enter para enviar, Shift+Enter para nueva línea" },
  "detail.complete": { en: "All done!", es: "¡Todo listo!" },
  "detail.deliveredOn": { en: "Delivered on", es: "Entregado el" },
  "detail.preparingFiles": { en: "Preparing {count} files...", es: "Preparando {count} archivos..." },
  "detail.downloadReady": { en: "Download ready!", es: "¡Descarga lista!" },
  "detail.revealAll": { en: "Reveal All", es: "Mostrar Todo" },
  "detail.uploading": { en: "Uploading...", es: "Subiendo..." },
  "detail.uploadDeliverables": { en: "Upload Designs", es: "Subir Diseños" },
  "detail.designsWillAppear": { en: "Your designs will show up here once they're ready.", es: "Tus diseños aparecerán aquí cuando estén listos." },
  "detail.noDeliverables": { en: "No designs for this request yet.", es: "Aún no hay diseños para esta solicitud." },
  "detail.startWorking": { en: "Start Working", es: "Empezar" },
  "detail.submitForReview": { en: "Submit for Review", es: "Enviar a Revisión" },
  "detail.markDone": { en: "Mark Done", es: "Marcar Entregado" },
  "detail.markDoneConfirm": { en: "Mark as done?", es: "¿Marcar como entregado?" },
  "detail.markDoneDesc": { en: "This marks the design as finished and delivered.", es: "Esto omite la revisión del cliente y marca la solicitud como completada." },
  "detail.cancel": { en: "Cancel", es: "Cancelar" },
  "detail.updating": { en: "Updating...", es: "Actualizando..." },
  "detail.approved": { en: "Approved! Your designs are ready to download.", es: "¡Aprobado! Tus diseños están listos para descargar." },
  "detail.statusUpdated": { en: "Status updated", es: "Estado actualizado" },
  "detail.couldntPost": { en: "Your message didn't send. Tap to try again.", es: "Tu mensaje no se envió. Toca para reintentar." },
  "detail.couldntUpdate": { en: "Something went wrong. Please try again.", es: "Algo salió mal. Inténtalo de nuevo." },
  "detail.hidden": { en: "Hidden", es: "Oculto" },
  "detail.vimistudio": { en: "Vimi Studio", es: "Vimi Studio" },
  "detail.client": { en: "Client", es: "Cliente" },

  // Quick feedback chips
  "chip.loveIt": { en: "Love it!", es: "¡Me encanta!" },
  "chip.changeColors": { en: "Can we change the colors?", es: "¿Cambiamos los colores?" },
  "chip.changeText": { en: "Can we change the text?", es: "¿Cambiamos el texto?" },
  "chip.differentLayout": { en: "Can we try a different layout?", es: "¿Probamos con otro layout?" },
  "chip.almostThere": { en: "Almost! Just a few tweaks", es: "¡Casi! Solo unos ajustes" },

  // Edit mode
  "edit.title": { en: "Edit Request", es: "Editar Solicitud" },
  "edit.heading": { en: "Edit this request", es: "Edita esta solicitud" },
  "edit.save": { en: "Save Changes", es: "Guardar Cambios" },
  "edit.saving": { en: "Saving...", es: "Guardando..." },
  "edit.cancel": { en: "Cancel", es: "Cancelar" },
  "edit.saved": { en: "Changes saved", es: "Cambios guardados" },

  // Missing strings (from audit)
  "detail.approveConfirm": { en: "Looks good to you?", es: "¿Te gusta cómo quedó?" },
  "detail.approveConfirmDesc": { en: "Once you approve, we'll get your files ready to download.", es: "Una vez que apruebes, prepararemos tus archivos para descargar." },
  "detail.uploadSuccess": { en: "Files uploaded!", es: "¡Archivos subidos!" },
  "detail.readyChip": { en: "READY FOR REVIEW", es: "LISTO PARA REVISAR" },
  "detail.reviewHero": { en: "Your designs are ready to review", es: "Tus diseños están listos para revisar" },
  "detail.reviewHeroSub": { en: "Take a look and let us know what you think", es: "Échalos un vistazo y dinos qué te parecen" },

  // Peak-End celebration modal
  "celebrate.title": { en: "Delivered & approved.", es: "Entregado y aprobado." },
  "celebrate.count": { en: "That's request #{n} together.", es: "Esa es la solicitud n.º {n} juntos." },
  "celebrate.countFallback": { en: "Another one delivered together.", es: "Otra entrega más, juntos." },
  "celebrate.ratedPrompt": { en: "How did this one feel?", es: "¿Qué tal estuvo esta?" },
  "celebrate.rated": { en: "rated this delivery", es: "calificó esta entrega" },
  "celebrate.thanks": { en: "Thanks for the feedback", es: "Gracias por tu opinión" },
  "celebrate.backToStudio": { en: "Back to studio", es: "Volver al estudio" },
  "celebrate.newRequest": { en: "Start a new request", es: "Nueva solicitud" },
  // Directions voting
  "detail.pickFavorite": { en: "Pick your favorite direction", es: "Elige tu dirección favorita" },
  "detail.pickSub": { en: "Swipe through options and tap the one you love", es: "Desliza entre opciones y elige la que más te guste" },
  "detail.pickThis": { en: "Pick This One", es: "Elegir Esta" },
  "detail.thisOne": { en: "This one!", es: "¡Esta!" },
  "detail.greatChoice": { en: "Great choice!", es: "¡Gran elección!" },
  "detail.willRefine": { en: "Your designer will refine this direction for you", es: "Tu diseñador refinará esta propuesta" },
  "detail.yourPick": { en: "Your Pick", es: "Tu Elección" },
  "detail.designersPick": { en: "Designer's Pick", es: "Favorita del Diseñador" },
  "detail.confirmVote": { en: "Confirm", es: "Confirmar" },
  "detail.confirming": { en: "Confirming...", es: "Confirmando..." },
  "detail.changeMyMind": { en: "Change My Mind", es: "Cambiar de Opinión" },
  "detail.addNote": { en: "Want to add a note for your designer? (optional)", es: "¿Quieres agregar una nota para tu diseñador? (opcional)" },
  "detail.tellDesigner": { en: "Tell your designer what you think...", es: "Dile a tu diseñador lo que piensas..." },
  "detail.seeOthers": { en: "See other directions", es: "Ver otras direcciones" },
  "detail.hideOthers": { en: "Hide other directions", es: "Ocultar otras direcciones" },
  "detail.waitingForPick": { en: "Waiting for client to pick a direction", es: "Esperando a que el cliente elija una dirección" },
  "detail.clientPicked": { en: "picked", es: "eligió" },

  // Carousel directions / story-driven voting (P1 polish from persona feedback)
  "directions.heroPick": {
    en: "Two stories. Which should we tell your audience?",
    es: "Dos propuestas. ¿Cuál le va mejor a tu marca?",
  },
  "directions.heroDone": { en: "The story is set ✨", es: "Ya decidiste ✨" },
  "directions.heroPickHint": {
    en: "Tap through each carousel like you would on Instagram, then pick the one that feels right.",
    es: "Desliza por cada carrusel como lo harías en Instagram, y elige la propuesta que más te guste.",
  },
  "directions.heroDoneHint": {
    en: "Your designer will refine this next.",
    es: "Tu diseñador refinará esta propuesta.",
  },
  "directions.pickStory": { en: "Choose this one", es: "Esta es la buena" },
  "directions.refining": {
    en: "✨ Your designer will refine this next",
    es: "✨ Tu diseñador refinará esta propuesta",
  },
  "directions.viewLarger": { en: "Tap to view larger", es: "Toca para ver más grande" },
  "directions.captionMore": { en: "more", es: "más" },
  "directions.captionLess": { en: "less", es: "menos" },
  "directions.option": { en: "Option", es: "Opción" },
} as const;
