/** New request form — 5-step wizard */
export const form = {
  "form.step.name": { en: "Name", es: "Nombre" },
  "form.step.type": { en: "Type", es: "Tipo" },
  "form.step.details": { en: "Details", es: "Detalles" },
  "form.step.timeline": { en: "Timeline", es: "Plazo" },
  "form.step.inspiration": { en: "Inspiration", es: "Inspiración" },

  "form.name.title": { en: "What do you need designed?", es: "¿Qué necesitas que diseñemos?" },
  "form.name.subtitle": { en: "A short name so your designer knows what to expect.", es: "Un nombre corto para que tu diseñador sepa qué esperar." },
  "form.name.placeholder": { en: "e.g. Instagram story templates, Logo refresh...", es: "ej. Plantillas para Instagram, Rediseño de logo..." },

  "form.type.title": { en: "What kind of project is this?", es: "¿Qué tipo de proyecto es?" },
  "form.type.subtitle": { en: "Pick the closest match. You can always add details later.", es: "Elige la opción más cercana. Siempre puedes agregar detalles después." },
  "form.type.logo": { en: "Logo Design", es: "Diseño de logo" },
  "form.type.logo.desc": { en: "A logo or icon for your brand", es: "Un logo o ícono para tu marca" },
  "form.type.social": { en: "Social Media", es: "Redes sociales" },
  "form.type.social.desc": { en: "Posts for Instagram, Facebook, TikTok...", es: "Publicaciones para Instagram, Facebook, TikTok..." },
  "form.type.web": { en: "Website", es: "Sitio web" },
  "form.type.web.desc": { en: "Web pages, banners, landing pages", es: "Páginas web, banners, landing pages" },
  "form.type.brand": { en: "Branding", es: "Branding" },
  "form.type.brand.desc": { en: "Colors, fonts, brand guidelines", es: "Colores, fuentes, guía de marca" },
  "form.type.presentation": { en: "Presentation", es: "Presentación" },
  "form.type.presentation.desc": { en: "Pitch decks, slides, one-pagers", es: "Presentaciones, slides, one-pagers" },
  "form.type.other": { en: "Something Else", es: "Otra cosa" },
  "form.type.other.desc": { en: "Anything else you need designed", es: "Cualquier otra cosa que necesites diseñar" },

  "form.details.title": { en: "Tell us a bit more", es: "Cuéntanos un poco más" },
  "form.details.subtitle": { en: "Don't worry about design terms — just describe what you're picturing. You can paste images too.", es: "No te preocupes por términos de diseño — solo describe lo que imaginas. También puedes pegar imágenes." },
  "form.details.placeholder": { en: "What's it for? (e.g. weekly specials on Instagram)\n\nAny colors or style you like? (e.g. warm, appetizing, our brand colors)\n\nAnything to avoid? (e.g. no blue, keep it simple)", es: "¿Para qué es? (ej. especiales semanales en Instagram)\n\n¿Algún color o estilo que te guste? (ej. cálido, apetitoso, colores de nuestra marca)\n\n¿Algo que evitar? (ej. sin azul, mantenerlo simple)" },

  "form.timeline.title": { en: "When do you need it?", es: "¿Cuándo lo necesitas?" },
  "form.timeline.subtitle": { en: "Let your designer know how soon you need it.", es: "Dile a tu diseñador qué tan pronto lo necesitas." },
  "form.timeline.dueDate": { en: "Due date", es: "Fecha límite" },
  "form.timeline.optional": { en: "optional", es: "opcional" },

  "form.priority.whenever": { en: "Whenever", es: "Cuando sea" },
  "form.priority.whenever.desc": { en: "No rush, take your time", es: "Sin prisa, tómate tu tiempo" },
  "form.priority.thisWeek": { en: "This Week", es: "Esta semana" },
  "form.priority.thisWeek.desc": { en: "Ready within the week", es: "Listo en la semana" },
  "form.priority.urgent": { en: "Urgent", es: "Urgente" },
  "form.priority.urgent.desc": { en: "Need it right away", es: "Lo necesito ya" },

  "form.inspiration.title": { en: "Any inspiration?", es: "¿Alguna inspiración?" },
  "form.inspiration.subtitle": { en: "Screenshots from Pinterest, Instagram, or anywhere work great. Or skip this step.", es: "Capturas de Pinterest, Instagram o donde sea van perfecto. O sáltate este paso." },
  "form.inspiration.addFile": { en: "Add file", es: "Agregar" },

  "form.continue": { en: "Continue", es: "Continuar" },
  "form.back": { en: "Back", es: "Atrás" },
  "form.submit": { en: "Send to Designer", es: "Enviar al diseñador" },
  "form.submitting": { en: "Sending...", es: "Enviando..." },
  "form.success.title": { en: "Got it!", es: "¡Listo!" },
  "form.success.body": { en: "Your designer will take it from here. We'll let you know when there's something to see.", es: "Tu diseñador se encarga desde aquí. Te avisaremos cuando haya algo que ver." },
  "form.error.title": { en: "Hmm, something went wrong", es: "Algo salió mal" },
  "form.error.body": { en: "We couldn't send your request. Please try again.", es: "No pudimos enviar tu solicitud. Inténtalo de nuevo." },
} as const;
