/** New request form — 5-step wizard */
export const form = {
  "form.step.name": { en: "Name", es: "Nombre" },
  "form.step.type": { en: "Type", es: "Tipo" },
  "form.step.details": { en: "Details", es: "Detalles" },
  "form.step.timeline": { en: "Timeline", es: "Plazo" },
  "form.step.inspiration": { en: "Inspiration", es: "Inspiración" },

  "form.name.title": { en: "What do you need designed?", es: "¿Qué necesitas que diseñemos?" },
  "form.name.subtitle": { en: "A short name so your designer knows what to expect.", es: "Un nombre corto para que tu diseñador sepa qué esperar." },
  "form.name.placeholder": { en: "e.g. Instagram story templates, Logo refresh...", es: "ej. Plantillas para Instagram, Rediseño de logo..." },

  "form.type.title": { en: "What do you need?", es: "¿Qué necesitas?" },
  "form.type.subtitle": { en: "Pick the closest match. You can always add details next.", es: "Elige la opción más cercana. Siempre puedes agregar detalles después." },
  "form.type.startFresh": { en: "Or start fresh", es: "O empieza de cero" },

  "form.essentials.title": { en: "Tell us the essentials", es: "Cuéntanos lo esencial" },
  "form.essentials.subtitle": { en: "Just what your designer needs to start — nothing more.", es: "Solo lo que tu diseñador necesita para empezar — nada más." },
  "form.essentials.titleLabel": { en: "Title", es: "Título" },
  "form.essentials.briefLabel": { en: "Brief", es: "Brief" },
  "form.essentials.timelineLabel": { en: "Timeline", es: "Plazo" },
  "form.essentials.needTitle": { en: "Add a title to continue", es: "Agrega un título para continuar" },

  "form.review.title": { en: "Looks right?", es: "¿Se ve bien?" },
  "form.review.subtitle": { en: "This lands directly with your designer.", es: "Esto llega directo a tu diseñador." },
  "form.reviewAndSend": { en: "Review & send", es: "Revisar y enviar" },
  "form.type.logo": { en: "Logo Design", es: "Diseño de logo" },
  "form.type.logo.desc": { en: "A logo or icon for your brand", es: "Un logo o ícono para tu marca" },
  "form.type.social": { en: "Social Media", es: "Redes sociales" },
  "form.type.social.desc": { en: "Posts for Instagram, Facebook, TikTok...", es: "Publicaciones para Instagram, Facebook, TikTok..." },
  "form.type.web": { en: "Website", es: "Sitio web" },
  "form.type.web.desc": { en: "Web pages, banners, landing pages", es: "Páginas web, banners, landing pages" },
  "form.type.brand": { en: "Branding", es: "Branding" },
  "form.type.brand.desc": { en: "Colors, fonts, brand guidelines", es: "Colores, fuentes, guía de marca" },
  "form.type.presentation": { en: "Presentation", es: "Presentación" },
  "form.type.presentation.desc": { en: "Pitch decks, slides, one-pagers", es: "Presentaciones, slides, one-pagers" },
  "form.type.other": { en: "Something Else", es: "Otra cosa" },
  "form.type.other.desc": { en: "Anything else you need designed", es: "Cualquier otra cosa que necesites diseñar" },

  "form.details.title": { en: "Tell us a bit more", es: "Cuéntanos un poco más" },
  "form.details.subtitle": { en: "Don't worry about design terms — just describe what you're picturing. You can paste images too.", es: "No te preocupes por términos de diseño — solo describe lo que imaginas. También puedes pegar imágenes." },
  "form.details.placeholder": { en: "What's it for?\n\nAny colors or style you like?\n\nAnything to avoid?", es: "¿Para qué es?\n\n¿Algún color o estilo que te guste?\n\n¿Algo que evitar?" },
  "form.details.placeholder.logo": { en: "Business name and tagline?\n\nColors you love or want to avoid?\n\nWhere will it go? (website, menu, signage, social...)", es: "Nombre del negocio y eslogan?\n\n¿Colores que te gusten o quieras evitar?\n\n¿Dónde se usará? (web, menú, letrero, redes...)" },
  "form.details.placeholder.social": { en: "Which platform? (Instagram, Facebook, TikTok...)\n\nWhat type of post? (story, feed, reel, carousel)\n\nWhat should it say or promote?", es: "¿Qué plataforma? (Instagram, Facebook, TikTok...)\n\n¿Qué tipo? (historia, feed, reel, carrusel)\n\n¿Qué debe decir o promocionar?" },
  "form.details.placeholder.web": { en: "Which page? (homepage, landing, menu...)\n\nDo you have a website already? Share the URL\n\nWhat content should go on it?", es: "¿Qué página? (inicio, landing, menú...)\n\n¿Ya tienes sitio web? Comparte la URL\n\n¿Qué contenido debe llevar?" },
  "form.details.placeholder.brand": { en: "What do you already have? (logo, colors, fonts)\n\nWhat's missing?\n\nWho's your audience?", es: "¿Qué ya tienes? (logo, colores, fuentes)\n\n¿Qué falta?\n\n¿Quién es tu audiencia?" },
  "form.details.placeholder.presentation": { en: "What's it about?\n\nHow many slides?\n\nAny data or content to include?", es: "¿De qué trata?\n\n¿Cuántas diapositivas?\n\n¿Datos o contenido que incluir?" },

  "form.timeline.title": { en: "When do you need it?", es: "¿Cuándo lo necesitas?" },
  "form.timeline.subtitle": { en: "Let your designer know how soon you need it.", es: "Dile a tu diseñador qué tan pronto lo necesitas." },
  "form.timeline.dueDate": { en: "Due date", es: "Fecha límite" },
  "form.timeline.optional": { en: "optional", es: "opcional" },

  "form.priority.whenever": { en: "Whenever", es: "Cuando sea" },
  "form.priority.whenever.desc": { en: "No rush, take your time", es: "Sin prisa, tómate tu tiempo" },
  "form.priority.thisWeek": { en: "This Week", es: "Esta semana" },
  "form.priority.thisWeek.desc": { en: "Ready within the week", es: "Listo en la semana" },
  "form.priority.urgent": { en: "Urgent", es: "Urgente" },
  "form.priority.urgent.desc": { en: "Need it right away", es: "Lo necesito ya" },

  "form.inspiration.title": { en: "Any inspiration?", es: "¿Alguna inspiración?" },
  "form.inspiration.subtitle": { en: "Screenshots from Pinterest, Instagram, or anywhere work great. Or skip this step.", es: "Capturas de Pinterest, Instagram o donde sea van perfecto. O sáltate este paso." },
  "form.inspiration.addFile": { en: "Add file", es: "Agregar" },

  "form.summary.heading": { en: "Quick review", es: "Revisión rápida" },
  "form.summary.request": { en: "Request", es: "Solicitud" },
  "form.summary.type": { en: "Type", es: "Tipo" },
  "form.summary.timeline": { en: "Timeline", es: "Plazo" },
  "form.summary.priority": { en: "Priority", es: "Prioridad" },
  "form.summary.untitled": { en: "Untitled request", es: "Solicitud sin título" },

  "form.continue": { en: "Continue", es: "Continuar" },
  "form.back": { en: "Back", es: "Atrás" },
  "form.submit": { en: "Send to Designer", es: "Enviar al diseñador" },
  "form.submitting": { en: "Sending...", es: "Enviando..." },
  "form.success.title": { en: "Got it!", es: "¡Listo!" },
  "form.success.body": { en: "Your designer will take it from here. We'll let you know when there's something to see.", es: "Tu diseñador se encarga desde aquí. Te avisaremos cuando haya algo que ver." },
  "form.error.title": { en: "Hmm, something went wrong", es: "Algo salió mal" },
  "form.error.body": { en: "We couldn't send your request. Please try again.", es: "No pudimos enviar tu solicitud. Inténtalo de nuevo." },
  "form.uploadFailed": { en: "{count} file{s} failed to upload. Your request was still submitted.", es: "{count} archivo{s} no se pudieron subir. Tu solicitud se envió de todos modos." },
} as const;
